import { connectDB } from './config/db'
import User from './models/User'
import Category from './models/Category'
import Product from './models/Product'

async function seed() {
  await connectDB()
  console.log('Connected to MongoDB')

  await User.deleteMany({})
  await Category.deleteMany({})
  await Product.deleteMany({})

  const admin = await User.create({
    name: 'Admin',
    email: 'admin@shopease.com',
    passwordHash: 'Admin@123',
    role: 'admin',
    isEmailVerified: true,
  })
  console.log('Admin created:', admin.email)

  const customer = await User.create({
    name: 'John Doe',
    email: 'john@example.com',
    passwordHash: 'Password@123',
    role: 'customer',
    isEmailVerified: true,
  })
  console.log('Customer created:', customer.email)

  const categories = await Category.insertMany([
    { name: 'Electronics', slug: 'electronics', icon: '💻', order: 1 },
    { name: 'Fashion', slug: 'fashion', icon: '👕', order: 2 },
    { name: 'Home & Living', slug: 'home-living', icon: '🏡', order: 3 },
    { name: 'Beauty', slug: 'beauty', icon: '💄', order: 4 },
    { name: 'Sports', slug: 'sports', icon: '⚽', order: 5 },
  ])
  console.log(`${categories.length} categories created`)

  const products = await Product.insertMany([
    {
      name: 'Wireless Bluetooth Headphones',
      slug: 'wireless-bluetooth-headphones',
      description: 'Premium wireless headphones with active noise cancellation, 30-hour battery life, and comfortable over-ear design. Features Bluetooth 5.0, built-in microphone, and foldable design for easy portability.',
      shortDescription: 'Premium ANC wireless headphones with 30hr battery',
      price: 129.99,
      discountPrice: 89.99,
      images: [
        'https://picsum.photos/seed/headphone1/800/800',
        'https://picsum.photos/seed/headphone2/800/800',
        'https://picsum.photos/seed/headphone3/800/800',
      ],
      category: categories[0]._id,
      brand: 'SoundMax',
      stock: 50,
      sold: 320,
      sku: 'ELEC-HP-001',
      tags: ['wireless', 'bluetooth', 'headphones', 'audio'],
      variants: [{ name: 'Color', options: ['Black', 'White', 'Blue'] }],
      specifications: [
        { key: 'Battery Life', value: '30 hours' },
        { key: 'Bluetooth', value: '5.0' },
        { key: 'Driver Size', value: '40mm' },
        { key: 'Weight', value: '250g' },
      ],
      ratingsAverage: 4.5,
      ratingsCount: 128,
      isFeatured: true,
    },
    {
      name: 'Smart Watch Pro',
      slug: 'smart-watch-pro',
      description: 'Advanced smartwatch with AMOLED display, GPS tracking, heart rate monitor, sleep tracking, and 7-day battery life. Water resistant to 50m.',
      shortDescription: 'AMOLED smartwatch with GPS and health tracking',
      price: 249.99,
      discountPrice: 199.99,
      images: [
        'https://picsum.photos/seed/watch1/800/800',
        'https://picsum.photos/seed/watch2/800/800',
      ],
      category: categories[0]._id,
      brand: 'TechWear',
      stock: 30,
      sold: 210,
      sku: 'ELEC-SW-001',
      tags: ['smartwatch', 'fitness', 'gps', 'wearable'],
      variants: [
        { name: 'Size', options: ['40mm', '44mm'] },
        { name: 'Color', options: ['Black', 'Silver'] },
      ],
      specifications: [
        { key: 'Display', value: '1.4" AMOLED' },
        { key: 'Battery', value: '7 days' },
        { key: 'Water Resistance', value: '50m' },
        { key: 'Sensors', value: 'HR, GPS, SpO2' },
      ],
      ratingsAverage: 4.3,
      ratingsCount: 95,
      isFeatured: true,
    },
    {
      name: 'Classic Cotton T-Shirt',
      slug: 'classic-cotton-t-shirt',
      description: 'Premium 100% organic cotton t-shirt with a relaxed fit. Pre-shrunk fabric, reinforced seams, and tagless neck label for maximum comfort.',
      shortDescription: '100% organic cotton relaxed fit t-shirt',
      price: 34.99,
      discountPrice: 24.99,
      images: [
        'https://picsum.photos/seed/tshirt1/800/800',
        'https://picsum.photos/seed/tshirt2/800/800',
      ],
      category: categories[1]._id,
      brand: 'EcoWear',
      stock: 200,
      sold: 1500,
      sku: 'FASH-TS-001',
      tags: ['cotton', 't-shirt', 'casual', 'organic'],
      variants: [
        { name: 'Size', options: ['S', 'M', 'L', 'XL', 'XXL'] },
        { name: 'Color', options: ['White', 'Black', 'Navy', 'Gray'] },
      ],
      specifications: [
        { key: 'Material', value: '100% Organic Cotton' },
        { key: 'Fit', value: 'Relaxed' },
        { key: 'Weight', value: '180 GSM' },
      ],
      ratingsAverage: 4.6,
      ratingsCount: 342,
      isFeatured: true,
    },
    {
      name: 'Running Shoes Ultra',
      slug: 'running-shoes-ultra',
      description: 'Lightweight running shoes with responsive cushioning, breathable mesh upper, and durable rubber outsole. Designed for road running with optimal energy return.',
      shortDescription: 'Lightweight responsive running shoes with mesh upper',
      price: 149.99,
      images: [
        'https://picsum.photos/seed/shoe1/800/800',
        'https://picsum.photos/seed/shoe2/800/800',
        'https://picsum.photos/seed/shoe3/800/800',
      ],
      category: categories[4]._id,
      brand: 'SportFlex',
      stock: 75,
      sold: 680,
      sku: 'SPRT-RS-001',
      tags: ['running', 'shoes', 'fitness', 'athletic'],
      variants: [
        { name: 'Size', options: ['7', '8', '9', '10', '11', '12'] },
        { name: 'Color', options: ['Black/Red', 'Blue/White', 'All Black'] },
      ],
      specifications: [
        { key: 'Weight', value: '280g' },
        { key: 'Drop', value: '8mm' },
        { key: 'Type', value: 'Road' },
        { key: 'Cushioning', value: 'Responsive' },
      ],
      ratingsAverage: 4.4,
      ratingsCount: 215,
      isFeatured: true,
    },
    {
      name: 'Stainless Steel Water Bottle',
      slug: 'stainless-steel-water-bottle',
      description: 'Double-wall vacuum insulated water bottle. Keeps drinks cold for 24 hours or hot for 12 hours. BPA-free, leak-proof lid with carrying loop.',
      shortDescription: 'Vacuum insulated 32oz bottle, cold 24hr / hot 12hr',
      price: 39.99,
      discountPrice: 29.99,
      images: [
        'https://picsum.photos/seed/bottle1/800/800',
      ],
      category: categories[2]._id,
      brand: 'EcoLiving',
      stock: 150,
      sold: 890,
      sku: 'HOME-WB-001',
      tags: ['bottle', 'water', 'insulated', 'eco-friendly'],
      variants: [
        { name: 'Size', options: ['24oz', '32oz', '40oz'] },
        { name: 'Color', options: ['Stainless', 'Matte Black', 'Ocean Blue'] },
      ],
      specifications: [
        { key: 'Material', value: '18/8 Stainless Steel' },
        { key: 'Capacity', value: '32oz / 946ml' },
        { key: 'Insulation', value: 'Double-wall vacuum' },
        { key: 'BPA Free', value: 'Yes' },
      ],
      ratingsAverage: 4.7,
      ratingsCount: 567,
      isFeatured: true,
    },
    {
      name: 'Hydrating Face Serum',
      slug: 'hydrating-face-serum',
      description: 'Advanced hydrating serum with hyaluronic acid and vitamin C. Lightweight formula that absorbs quickly, leaving skin plump and radiant. Suitable for all skin types.',
      shortDescription: 'Hyaluronic acid + vitamin C hydrating serum',
      price: 44.99,
      images: [
        'https://picsum.photos/seed/serum1/800/800',
      ],
      category: categories[3]._id,
      brand: 'GlowLab',
      stock: 100,
      sold: 430,
      sku: 'BEAUT-SR-001',
      tags: ['skincare', 'serum', 'hydrating', 'vitamin c'],
      variants: [
        { name: 'Size', options: ['30ml', '50ml'] },
      ],
      specifications: [
        { key: 'Key Ingredients', value: 'Hyaluronic Acid, Vitamin C' },
        { key: 'Skin Type', value: 'All' },
        { key: 'Volume', value: '30ml / 1oz' },
      ],
      ratingsAverage: 4.5,
      ratingsCount: 178,
      isFeatured: false,
    },
    {
      name: 'Leather Messenger Bag',
      slug: 'leather-messenger-bag',
      description: 'Genuine leather messenger bag with padded laptop compartment. Features multiple organizer pockets, adjustable shoulder strap, and brass hardware.',
      shortDescription: 'Genuine leather bag with laptop compartment',
      price: 189.99,
      discountPrice: 149.99,
      images: [
        'https://picsum.photos/seed/bag1/800/800',
        'https://picsum.photos/seed/bag2/800/800',
      ],
      category: categories[1]._id,
      brand: 'LeatherCraft',
      stock: 40,
      sold: 156,
      sku: 'FASH-BG-001',
      tags: ['leather', 'bag', 'messenger', 'laptop'],
      variants: [
        { name: 'Color', options: ['Brown', 'Black', 'Tan'] },
      ],
      specifications: [
        { key: 'Material', value: 'Genuine Leather' },
        { key: 'Laptop Size', value: 'Up to 15.6"' },
        { key: 'Strap', value: 'Adjustable' },
      ],
      ratingsAverage: 4.3,
      ratingsCount: 89,
      isFeatured: false,
    },
    {
      name: 'Wireless Charging Pad',
      slug: 'wireless-charging-pad',
      description: 'Fast wireless charging pad compatible with all Qi-enabled devices. Supports up to 15W fast charge, with LED indicator and anti-slip design.',
      shortDescription: '15W fast Qi wireless charger with LED indicator',
      price: 29.99,
      images: [
        'https://picsum.photos/seed/charger1/800/800',
      ],
      category: categories[0]._id,
      brand: 'TechWear',
      stock: 90,
      sold: 670,
      sku: 'ELEC-CH-001',
      tags: ['charger', 'wireless', 'qi', 'fast-charge'],
      variants: [
        { name: 'Color', options: ['Black', 'White'] },
      ],
      specifications: [
        { key: 'Output', value: '15W max' },
        { key: 'Compatibility', value: 'All Qi devices' },
        { key: 'Input', value: 'USB-C' },
      ],
      ratingsAverage: 4.2,
      ratingsCount: 234,
      isFeatured: false,
    },
    {
      name: 'Yoga Mat Premium',
      slug: 'yoga-mat-premium',
      description: 'Extra thick 6mm yoga mat with alignment lines. Made from eco-friendly TPE material, non-slip surface, and includes carrying strap.',
      shortDescription: '6mm eco-friendly TPE yoga mat with alignment lines',
      price: 49.99,
      discountPrice: 39.99,
      images: [
        'https://picsum.photos/seed/yoga1/800/800',
      ],
      category: categories[4]._id,
      brand: 'SportFlex',
      stock: 60,
      sold: 345,
      sku: 'SPRT-YM-001',
      tags: ['yoga', 'fitness', 'mat', 'exercise'],
      variants: [
        { name: 'Color', options: ['Purple', 'Blue', 'Green', 'Pink'] },
      ],
      specifications: [
        { key: 'Thickness', value: '6mm' },
        { key: 'Material', value: 'TPE (Eco-friendly)' },
        { key: 'Dimensions', value: '183 x 61 cm' },
        { key: 'Weight', value: '1.2kg' },
      ],
      ratingsAverage: 4.6,
      ratingsCount: 198,
      isFeatured: false,
    },
    {
      name: 'Scented Candle Set',
      slug: 'scented-candle-set',
      description: 'Set of 3 hand-poured soy wax candles in premium glass jars. Scents: Vanilla Lavender, Fresh Linen, and Warm Amber. Each burns for 45+ hours.',
      shortDescription: 'Set of 3 soy wax candles, 45hr burn each',
      price: 54.99,
      images: [
        'https://picsum.photos/seed/candle1/800/800',
      ],
      category: categories[2]._id,
      brand: 'EcoLiving',
      stock: 35,
      sold: 267,
      sku: 'HOME-CN-001',
      tags: ['candle', 'scented', 'soy', 'home-decor'],
      variants: [
        { name: 'Scent Set', options: ['Relaxation', 'Fresh Home', 'Warm Cozy'] },
      ],
      specifications: [
        { key: 'Material', value: '100% Soy Wax' },
        { key: 'Burn Time', value: '45+ hours each' },
        { key: 'Size', value: '200g each' },
      ],
      ratingsAverage: 4.8,
      ratingsCount: 156,
      isFeatured: true,
    },
    {
      name: 'Noise Cancelling Earbuds',
      slug: 'noise-cancelling-earbuds',
      description: 'True wireless earbuds with adaptive noise cancellation, IPX5 water resistance, and 24-hour total battery life with charging case.',
      shortDescription: 'True wireless ANC earbuds with 24hr battery',
      price: 179.99,
      discountPrice: 139.99,
      images: [
        'https://picsum.photos/seed/earbuds1/800/800',
        'https://picsum.photos/seed/earbuds2/800/800',
      ],
      category: categories[0]._id,
      brand: 'SoundMax',
      stock: 45,
      sold: 412,
      sku: 'ELEC-EB-001',
      tags: ['earbuds', 'wireless', 'noise-cancelling', 'audio'],
      variants: [
        { name: 'Color', options: ['White', 'Black', 'Navy'] },
      ],
      specifications: [
        { key: 'Battery', value: '6hr buds + 18hr case' },
        { key: 'Water Resistance', value: 'IPX5' },
        { key: 'ANC', value: 'Adaptive' },
        { key: 'Driver', value: '12mm' },
      ],
      ratingsAverage: 4.4,
      ratingsCount: 289,
      isFeatured: true,
    },
    {
      name: 'Knit Sweater',
      slug: 'knit-sweater',
      description: 'Warm and cozy knit sweater made from a soft merino wool blend. Features ribbed cuffs and hem, and a classic crew neck design.',
      shortDescription: 'Merino wool blend crew neck knit sweater',
      price: 79.99,
      discountPrice: 59.99,
      images: [
        'https://picsum.photos/seed/sweater1/800/800',
      ],
      category: categories[1]._id,
      brand: 'EcoWear',
      stock: 80,
      sold: 534,
      sku: 'FASH-KN-001',
      tags: ['sweater', 'knit', 'wool', 'winter'],
      variants: [
        { name: 'Size', options: ['S', 'M', 'L', 'XL'] },
        { name: 'Color', options: ['Cream', 'Gray', 'Burgundy', 'Forest Green'] },
      ],
      specifications: [
        { key: 'Material', value: '60% Merino Wool, 40% Acrylic' },
        { key: 'Fit', value: 'Regular' },
        { key: 'Care', value: 'Hand wash cold' },
      ],
      ratingsAverage: 4.5,
      ratingsCount: 189,
      isFeatured: false,
    },
    {
      name: 'Protein Powder - Vanilla',
      slug: 'protein-powder-vanilla',
      description: 'Premium whey protein isolate with natural vanilla flavor. 25g protein per serving, low sugar, and mixes instantly. Ideal for post-workout recovery.',
      shortDescription: 'Whey protein isolate, 25g protein, vanilla',
      price: 49.99,
      images: [
        'https://picsum.photos/seed/protein1/800/800',
      ],
      category: categories[4]._id,
      brand: 'SportFlex',
      stock: 120,
      sold: 890,
      sku: 'SPRT-PP-001',
      tags: ['protein', 'fitness', 'supplement', 'whey'],
      variants: [
        { name: 'Size', options: ['1lb', '2lb', '5lb'] },
        { name: 'Flavor', options: ['Vanilla', 'Chocolate', 'Strawberry'] },
      ],
      specifications: [
        { key: 'Protein', value: '25g per serving' },
        { key: 'Type', value: 'Whey Protein Isolate' },
        { key: 'Carbs', value: '2g per serving' },
        { key: 'Serving Size', value: '31g' },
      ],
      ratingsAverage: 4.3,
      ratingsCount: 456,
      isFeatured: false,
    },
    {
      name: 'Desk LED Lamp',
      slug: 'desk-led-lamp',
      description: 'Adjustable LED desk lamp with 5 color modes and 7 brightness levels. Flexible gooseneck design, USB charging port, and auto-off timer.',
      shortDescription: 'Adjustable LED lamp with 5 color modes & USB port',
      price: 44.99,
      discountPrice: 34.99,
      images: [
        'https://picsum.photos/seed/lamp1/800/800',
      ],
      category: categories[2]._id,
      brand: 'EcoLiving',
      stock: 65,
      sold: 378,
      sku: 'HOME-LM-001',
      tags: ['lamp', 'led', 'desk', 'lighting'],
      variants: [
        { name: 'Color', options: ['White', 'Black'] },
      ],
      specifications: [
        { key: 'Brightness', value: '7 levels' },
        { key: 'Color Modes', value: '5 (Warm to Cool)' },
        { key: 'Power', value: 'USB-C' },
        { key: 'Material', value: 'Aluminum + ABS' },
      ],
      ratingsAverage: 4.4,
      ratingsCount: 167,
      isFeatured: false,
    },
    {
      name: 'Moisturizing Face Cream',
      slug: 'moisturizing-face-cream',
      description: 'Rich yet lightweight moisturizer with ceramides and niacinamide. Strengthens skin barrier, provides 24-hour hydration, and improves skin texture.',
      shortDescription: 'Ceramide-rich 24hr moisturizer with niacinamide',
      price: 38.99,
      images: [
        'https://picsum.photos/seed/cream1/800/800',
      ],
      category: categories[3]._id,
      brand: 'GlowLab',
      stock: 85,
      sold: 312,
      sku: 'BEAUT-CR-001',
      tags: ['moisturizer', 'skincare', 'face-cream', 'hydration'],
      variants: [
        { name: 'Size', options: ['50ml', '100ml'] },
      ],
      specifications: [
        { key: 'Key Ingredients', value: 'Ceramides, Niacinamide' },
        { key: 'Skin Type', value: 'All, especially dry' },
        { key: 'Hydration', value: '24 hours' },
        { key: 'SPF', value: 'None' },
      ],
      ratingsAverage: 4.6,
      ratingsCount: 234,
      isFeatured: false,
    },
    {
      name: 'Portable Bluetooth Speaker',
      slug: 'portable-bluetooth-speaker',
      description: 'Waterproof portable Bluetooth speaker with 360° sound, 20-hour battery life, and built-in microphone. IP67 rated for outdoor use.',
      shortDescription: 'IP67 waterproof 360° speaker with 20hr battery',
      price: 69.99,
      discountPrice: 54.99,
      images: [
        'https://picsum.photos/seed/speaker1/800/800',
        'https://picsum.photos/seed/speaker2/800/800',
      ],
      category: categories[0]._id,
      brand: 'SoundMax',
      stock: 55,
      sold: 445,
      sku: 'ELEC-SP-001',
      tags: ['speaker', 'bluetooth', 'portable', 'waterproof'],
      variants: [
        { name: 'Color', options: ['Black', 'Red', 'Blue', 'Green'] },
      ],
      specifications: [
        { key: 'Battery', value: '20 hours' },
        { key: 'Waterproof', value: 'IP67' },
        { key: 'Bluetooth', value: '5.3' },
        { key: 'Output', value: '30W' },
      ],
      ratingsAverage: 4.5,
      ratingsCount: 378,
      isFeatured: true,
    },
    {
      name: 'Denim Jacket',
      slug: 'denim-jacket',
      description: 'Classic denim jacket in medium wash. Features button front closure, chest pockets, and adjustable waist tabs. A timeless wardrobe staple.',
      shortDescription: 'Classic medium wash denim jacket with pockets',
      price: 89.99,
      images: [
        'https://picsum.photos/seed/jacket1/800/800',
        'https://picsum.photos/seed/jacket2/800/800',
      ],
      category: categories[1]._id,
      brand: 'EcoWear',
      stock: 45,
      sold: 267,
      sku: 'FASH-DJ-001',
      tags: ['denim', 'jacket', 'casual', 'classic'],
      variants: [
        { name: 'Size', options: ['S', 'M', 'L', 'XL'] },
      ],
      specifications: [
        { key: 'Material', value: '100% Cotton Denim' },
        { key: 'Fit', value: 'Regular' },
        { key: 'Wash', value: 'Medium' },
        { key: 'Care', value: 'Machine wash cold' },
      ],
      ratingsAverage: 4.3,
      ratingsCount: 145,
      isFeatured: false,
    },
    {
      name: 'Scented Body Wash',
      slug: 'scented-body-wash',
      description: 'Luxurious body wash with natural essential oils. Sulfate-free formula that gently cleanses while nourishing the skin with aloe vera and vitamin E.',
      shortDescription: 'Sulfate-free body wash with aloe & vitamin E',
      price: 18.99,
      images: [
        'https://picsum.photos/seed/wash1/800/800',
      ],
      category: categories[3]._id,
      brand: 'GlowLab',
      stock: 110,
      sold: 678,
      sku: 'BEAUT-BW-001',
      tags: ['body-wash', 'skincare', 'shower', 'essential-oils'],
      variants: [
        { name: 'Scent', options: ['Lavender', 'Eucalyptus', 'Citrus'] },
        { name: 'Size', options: ['250ml', '500ml'] },
      ],
      specifications: [
        { key: 'Key Ingredients', value: 'Aloe Vera, Vitamin E' },
        { key: 'Free From', value: 'Sulfates, Parabens' },
        { key: 'Volume', value: '250ml' },
      ],
      ratingsAverage: 4.4,
      ratingsCount: 234,
      isFeatured: false,
    },
    {
      name: 'Resistance Bands Set',
      slug: 'resistance-bands-set',
      description: 'Set of 5 resistance bands with different tension levels. Includes carrying bag and exercise guide. Made from natural latex for durability.',
      shortDescription: '5-piece resistance band set with bag & guide',
      price: 24.99,
      discountPrice: 19.99,
      images: [
        'https://picsum.photos/seed/bands1/800/800',
      ],
      category: categories[4]._id,
      brand: 'SportFlex',
      stock: 95,
      sold: 567,
      sku: 'SPRT-RB-001',
      tags: ['fitness', 'resistance', 'bands', 'exercise'],
      variants: [
        { name: 'Resistance', options: ['Light', 'Medium', 'Heavy'] },
      ],
      specifications: [
        { key: 'Material', value: 'Natural Latex' },
        { key: 'Bands', value: '5 levels' },
        { key: 'Includes', value: 'Bag + Exercise Guide' },
        { key: 'Length', value: '120cm each' },
      ],
      ratingsAverage: 4.2,
      ratingsCount: 345,
      isFeatured: false,
    },
    {
      name: 'Ceramic Mug Set',
      slug: 'ceramic-mug-set',
      description: 'Set of 4 premium ceramic mugs with minimalist design. Microwave and dishwasher safe. Capacity 350ml each. Perfect for everyday use.',
      shortDescription: 'Set of 4 minimalist ceramic mugs, 350ml each',
      price: 32.99,
      images: [
        'https://picsum.photos/seed/mug1/800/800',
      ],
      category: categories[2]._id,
      brand: 'EcoLiving',
      stock: 70,
      sold: 456,
      sku: 'HOME-MG-001',
      tags: ['mug', 'ceramic', 'kitchen', 'set'],
      variants: [
        { name: 'Color Set', options: ['Neutral', 'Pastel', 'Bold'] },
      ],
      specifications: [
        { key: 'Material', value: 'Premium Ceramic' },
        { key: 'Capacity', value: '350ml / 12oz' },
        { key: 'Dishwasher Safe', value: 'Yes' },
        { key: 'Microwave Safe', value: 'Yes' },
      ],
      ratingsAverage: 4.7,
      ratingsCount: 189,
      isFeatured: false,
    },
  ])
  console.log(`${products.length} products created`)
  console.log('Seed completed!')
  process.exit(0)
}

seed().catch((err) => {
  console.error('Seed failed:', err)
  process.exit(1)
})
